---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/autoscaler