---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 10m0s
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.10.4
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
  values:
    autoDiscovery:
      clusterName: sandbox
    rbac:
      serviceAccount:
        create: false
        name: cluster-autoscaler
  install: {}