apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: flux-system
spec:
  releaseName: app1
  targetNamespace: app1
  storageNamespace: app1
  interval: 10s
  chart:
    spec:
      chart: hello-world
      # version: 5.9.2
      sourceRef:
        kind: HelmRepository
        name: sample-chart
  values:
    replicaCount: 1
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
  install: {}
