---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 10m0s
  chart:
    spec:
      chart: metrics-server
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    apiService:
      create: true
  install: {}
